# -*- coding: utf-8 -*-
"""Task09.ipynb
Automatically generated by Colab.
**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "../rdf/"
from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"data03.rdf", format="xml")
g2.parse(github_storage+"data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

